# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.

name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
      tags:
        - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    name: "Release"
    # The type of runner that the job will run on
    runs-on: "ubuntu-latest"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: "marvinpinto/action-automatic-release@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
